/**
 * @file migrations.c
 * @brief Implementation of the atomic migration engine
 * @copyright Real Estate Management System
 */
#include "migrations.h"
#include "db_connection.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Auto-generated by CMake at configure time
#include "migration_manifest.h"

// Check if migration has already been applied
static int is_migration_applied(const char* filename, int* is_applied) {
    sqlite3_stmt* stmt = NULL;
    int rc = db_prepare("SELECT 1 FROM schema_migrations WHERE name = ?;", &stmt);
    if (rc != 0) return rc;
    
    sqlite3_bind_text(stmt, 1, filename, -1, SQLITE_TRANSIENT);
    
    int step_rc = sqlite3_step(stmt);
    if (step_rc == SQLITE_ROW) {
        *is_applied = 1;
    } else {
        *is_applied = 0;
    }
    
    sqlite3_finalize(stmt);
    return 0; // RE_OK
}

// Mark migration as applied in the database
static int mark_migration_applied(const char* filename) {
    sqlite3_stmt* stmt = NULL;
    int rc = db_prepare("INSERT INTO schema_migrations (name, applied_at, checksum) VALUES (?, datetime('now'), 'checksum');", &stmt);
    if (rc != 0) return rc;
    
    sqlite3_bind_text(stmt, 1, filename, -1, SQLITE_TRANSIENT);
    
    int step_rc = sqlite3_step(stmt);
    sqlite3_finalize(stmt);
    
    if (step_rc != SQLITE_DONE) {
        return db_map_error(step_rc);
    }
    return 0; // RE_OK
}

static char* read_file_content(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    char* content = (char*)malloc((size_t)size + 1);
    if (content) {
        size_t read_bytes = fread(content, 1, (size_t)size, f);
        content[read_bytes] = '\0';
    }
    fclose(f);
    return content;
}

int migrations_run_all(const char* migrations_dir) {
    // 1. Create schema_migrations table if not exists
    const char* init_sql = 
        "CREATE TABLE IF NOT EXISTS schema_migrations ("
        "version INTEGER PRIMARY KEY AUTOINCREMENT, "
        "name TEXT NOT NULL UNIQUE, "
        "applied_at TEXT NOT NULL, "
        "checksum TEXT NOT NULL"
        ");";
    
    int rc = db_execute(init_sql);
    if (rc != 0) return rc;
    
    // 2. Iterate through migration manifest (generated securely by CMake, preventing directory traversal in C)
    for (int i = 0; migration_files[i] != NULL; ++i) {
        const char* filename = migration_files[i];
        
        // Extract just the basename safely
        const char* basename = filename;
        const char* slash = strrchr(filename, '/');
        if (slash) basename = slash + 1;
        const char* backslash = strrchr(basename, '\\');
        if (backslash) basename = backslash + 1;
        
        int applied = 0;
        rc = is_migration_applied(basename, &applied);
        if (rc != 0) return rc;
        
        if (applied) {
            continue; // Skip already applied migrations
        }
        
        // Construct full path securely
        char filepath[512];
        snprintf(filepath, sizeof(filepath), "%s/%s", migrations_dir, basename);
        
        char* sql_content = read_file_content(filepath);
        if (!sql_content) {
            return -99; // File read error (RE_ERR_INTERNAL)
        }
        
        // ATOMIC EXECUTION: BEGIN -> EXECUTE -> MARK APPLIED -> COMMIT
        rc = db_begin_transaction();
        if (rc != 0) {
            free(sql_content);
            return rc;
        }
        
        rc = db_execute(sql_content);
        free(sql_content);
        
        if (rc != 0) {
            db_rollback_transaction();
            return rc; // Migration failed, completely rolled back
        }
        
        rc = mark_migration_applied(basename);
        if (rc != 0) {
            db_rollback_transaction();
            return rc;
        }
        
        rc = db_commit_transaction();
        if (rc != 0) {
            return rc; // Commit failed
        }
    }
    
    return 0; // RE_OK
}
