/**
 * @file test_migrations.c
 * @brief Unit tests for atomic migration engine
 * @copyright Real Estate Management System
 */
#include "migrations.h"
#include "db_connection.h"
#include <stdio.h>
#include <assert.h>

int main() {
    printf("Running test_migrations...\n");
    
    int rc = db_init(":memory:", 5000);
    assert(rc == 0);
    
    // Note: Actual testing of migrations requires a manifest generated by CMake.
    // rc = migrations_run_all("../../migrations");
    
    db_close();
    
    printf("test_migrations PASSED\n");
    return 0;
}
